name: Sync Fork with Upstream

on:
  schedule:
    - cron: '0 4 * * *' # Runs every day at 04:00 UTC
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add upstream remote
        run: git remote add upstream https://github.com/vllm-project/vllm.git

      - name: Fetch upstream
        run: git fetch upstream

      - name: Merge upstream changes
        run: |
          git checkout main
          git merge upstream/main --allow-unrelated-histories --no-edit || true

      - name: Push changes to your fork
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: git push origin main
