# CI-friendly defaults for CUDA 13 development builds
cuda:
  version: "13.0.0"
  tag: "latest"
  base_flavor: "rockylinux9"
ubi:
  version: "9"
  tag: "latest"
python:
  version: "3.12"
  tag: "latest"
vllm:
  tag: main
arch:
  torch_cuda_arch_list: "8.0 8.6 8.9 9.0 12.0 13.0"
  cuda_archs: "80;86;89;90;120"
