name: Sync with Upstream

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config --global user.name 'Zhuul'
          git config --global user.email '40538530+Zhuul@users.noreply.github.com'

      - name: Add upstream remote
        run: git remote add upstream https://github.com/vllm-project/vllm.git

      - name: Fetch upstream changes
        run: git fetch upstream

      - name: Merge upstream changes
        id: merge
        run: |
          git checkout main
          git merge upstream/main --allow-unrelated-histories --no-edit || {
            echo "Merge conflict detected. Creating a new branch for manual resolution."
            BRANCH="merge-conflict-$(date +%Y%m%d%H%M%S)"
            git checkout -b "$BRANCH"
            # Push with a descriptive message
            git push origin HEAD
            echo "conflict=true" >> "$GITHUB_OUTPUT"
            echo "conflict_branch=$BRANCH" >> "$GITHUB_OUTPUT"
            exit 1
          }
          echo "conflict=false" >> "$GITHUB_OUTPUT"

      - name: Check for workflow file changes
        id: workflow_change
        run: |
          if git diff --name-only upstream/main | grep '^.github/workflows/'; then
            echo "workflow_changed=true" >> "$GITHUB_OUTPUT"
          else
            echo "workflow_changed=false" >> "$GITHUB_OUTPUT"
          fi

      # Use GITHUB_TOKEN for authentication, sufficient for repo write access in actions
      - name: Set up authentication
        run: git remote set-url origin "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/Zhuul/vllm.git"

      - name: Push changes if no workflow files changed
        if: steps.workflow_change.outputs.workflow_changed == 'false' && steps.merge.outputs.conflict == 'false'
        run: git push origin main

      - name: Create Pull Request for workflow file changes
        if: steps.workflow_change.outputs.workflow_changed == 'true' && steps.merge.outputs.conflict == 'false'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Sync with upstream: update workflow files"
          title: "Sync with upstream: update workflow files"
          body: |
            This PR was automatically created because workflow files were updated while syncing with upstream.
            Please review and merge.
          branch: workflow-sync-${{ github.run_id }}
          base: main

      # Notification step: create an issue if merge conflict detected
      - name: Create Issue on Merge Conflict
        if: steps.merge.outputs.conflict == 'true'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: "Merge Conflict Detected During Upstream Sync",
              body: `
              A merge conflict occurred while syncing with upstream (vllm-project/vllm).
              Branch for manual resolution: ${{ steps.merge.outputs.conflict_branch }}

              Please resolve this conflict at https://github.com/${context.repo.owner}/${context.repo.repo}/tree/${{ steps.merge.outputs.conflict_branch }}

              This issue was automatically created by the sync workflow.
              `
            })

      - name: Log completion
        run: echo "Sync with upstream completed. Thank you for using automated upstream sync 🚀"
